apiVersion: v1
kind: Pod
metadata:
  name: metrics-stack
  labels:
    app: metrics-stack
  annotations:
    io.podman.annotations.restart-policy: "always"
spec:
  containers:
    - name: graphite
      image: graphiteapp/graphite-statsd:latest
      ports:
        - containerPort: 80
          hostPort: 8080
          protocol: TCP
        - containerPort: 2003
          hostPort: 2003
          protocol: TCP
        - containerPort: 2004
          hostPort: 2004
          protocol: TCP
        - containerPort: 8125
          hostPort: 8125
          protocol: UDP
      volumeMounts:
        - name: graphite-storage
          mountPath: /opt/graphite/storage
        - name: graphite-schemas
          mountPath: /opt/graphite/conf/storage-schemas.conf
          subPath: storage-schemas.conf
        - name: graphite-aggregation
          mountPath: /opt/graphite/conf/storage-aggregation.conf
          subPath: storage-aggregation.conf

    - name: grafana
      image: grafana/grafana:10.4.5
      env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
      ports:
        - containerPort: 3000
          hostPort: 3000
          protocol: TCP
      volumeMounts:
        - name: grafana-provisioning
          mountPath: /etc/grafana/provisioning
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards

    - name: telegraf
      image: docker.io/library/telegraf:1.30
      args: ["--config-directory", "/etc/telegraf/telegraf.d"]
      ports:
        - containerPort: 8088
          protocol: TCP
      volumeMounts:
        - name: telegraf-conf
          mountPath: /etc/telegraf/telegraf.d

    - name: nginx
      image: docker.io/library/nginx:1.25-alpine
      ports:
        - containerPort: 443
          hostPort: 443
          protocol: TCP
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-certs
          mountPath: /etc/nginx/certs

  volumes:
    - name: graphite-storage
      hostPath:
        path: ./graphite/data
        type: Directory
    - name: graphite-schemas
      hostPath:
        path: ./graphite/storage-schemas.conf
        type: File
    - name: graphite-aggregation
      hostPath:
        path: ./graphite/storage-aggregation.conf
        type: File
    - name: grafana-provisioning
      hostPath:
        path: ./grafana/provisioning
        type: Directory
    - name: grafana-dashboards
      hostPath:
        path: ./grafana/dashboards
        type: Directory
    - name: telegraf-conf
      hostPath:
        path: ./telegraf
        type: Directory
    - name: nginx-conf
      hostPath:
        path: ./nginx/nginx.conf
        type: File
    - name: nginx-certs
      hostPath:
        path: ./nginx/certs
        type: Directory
