apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: true
    jsonData:
      organization: example-org
      defaultBucket: example-bucket
      httpMode: POST
    secureJsonData:
      token: example-token
